### ISSUE TITLE
Rearranging CSI based on perm - (get_csi_streams.m)

### ISSUE THREAD

**Issue by meer1992** [brunosoaresds/csi-monitor#1]
Hi @brunosoaresds ,
Thank you for sharing us the work. Really appreciate it.

I have a question regarding CSI sampling from this [file](https://github.com/brunosoaresds/csi-monitor/blob/master/csi-monitor-gui/get_csi_streams.m#L17). Do you reckon that permutation matrix should be done before sampling it similar the one in [here](https://github.com/meer1992/Realtime-processing-for-csitool/blob/master/matlab/read_bf_socket.m#L79)?
Regards

**Comment by brunosoaresds** [comment]
Closing it because is duplicated #1
