### ISSUE TITLE
csi-device-manager on OpenWRT

### ISSUE THREAD

**Issue by fathanpranaya** [brunosoaresds/csi-monitor#10]
Is it possible to use this tool if I use OpenWRT Router? If so, how to compile the tool and integrate it with OpenWRT source code? Thank you

**Comment by fathanpranaya** [comment]
Is it as simple as copy paste the CSI-MONITOR's csi-device-manager folder to OpenWRT-Source-Code's package folder?

**Comment by brunosoaresds** [comment]
Helo @fathanpranaya,

Yeah, i think its possible, but you will need to edit the device manager to operate on opewrt infrastructure (to save the files correctly). After, you need to edit the python layer to connect on each second on openwrt router and get the csi files. I think is it.

**Comment by fathanpranaya** [comment]
Thank you for your response
