### ISSUE TITLE
Rearranging CSI based on perm

### ISSUE THREAD

**Issue by meer1992** [brunosoaresds/csi-monitor#2]
Hi @brunosoaresds ,
Thank you for sharing us the work. Really appreciate it.

I have a question regarding CSI sampling from this [file](https://github.com/brunosoaresds/csi-monitor/blob/master/csi-monitor-gui/get_csi_streams.m#L17). Do you reckon that permutation matrix should be done before sampling it similar the one in [here](https://github.com/meer1992/Realtime-processing-for-csitool/blob/master/matlab/read_bf_socket.m#L79)?
Regards

**Comment by brunosoaresds** [comment]
Hello @meer1992,

I don't know if i understand correctly your question, but in [this file](https://github.com/brunosoaresds/csi-monitor/blob/master/csi-monitor-gui/get_csi_streams.m#L17) we get the CSI data cells obtained from the extractor tool and separate the csi matrix (complex values for each subcarrier) in each antenna pair. Our objective here is to plot, in real time, the CSI streams magnitude over the time. This [project/file](https://github.com/meer1992/Realtime-processing-for-csitool/blob/master/matlab/read_bf_socket.m#L79) on the other hand, plots the subcarriers magnitude on each antenna pair, is a different visualization.

**Comment by meer1992** [comment]
Aha. That makes sense. 
Thanks again
