### ISSUE TITLE
Epoch/Unix timestamp in received csi data

### ISSUE THREAD

**Issue by junstriker** [brunosoaresds/csi-monitor#3]
Hello,
I was wondering if in addition to the radio timestamp available in the atheros csi tool, can an epoch/unix timestamp be included for each packet received? If yes, I would be really grateful if you can explain to me how can that be done.
Thanks for your amazing work in building the real-time monitor tool and making it available. Is it possible to install this tool on an AP running OpenWrt, or it it applicable only to 2 PCs running the Ubuntu version of the atheros csi tool, with one configured as AP with hostapd?

Many thanks.
Kind regards

**Comment by brunosoaresds** [comment]
Hello @junstriker,

What do you mean with "epoch/unix timestamp"? The CSI packet timestamp is a epoch unix timestamp. Why you can't just use it?

About the installation, i have only deployed the application on 2 PCs, but if you can change the collector (csi-device-manager) to get the information from the AP, i don't think that is a problem to the monitor tool. Unfortunately there is needed a change in the device manager.

Best.,

**Comment by junstriker** [comment]
Hello @brunosoaresds 
Thank you for your reply.
For example, for the first packet I get the value of 2.5582e9 microseconds, and the next one is 2.5583e9. These do not convert to the present human date/time. So I'm wondering what these values actually mean.

**Comment by brunosoaresds** [comment]
@junstriker,

I think that in the ubuntu version this information is the unix timestamp. Maybe that is a openwrt issue, but i think that u can convert it to a unix timestamp, we just need to know what exactly is it.

What is the purpose of this information for you?
