### ISSUE TITLE
Installing csi-device-manager on ubuntu 16.04 Error

### ISSUE THREAD

**Issue by RusifE** [brunosoaresds/csi-monitor#4]
Hello,

I am trying to install CSI on my ubuntu 16.4. I have Matlab and Python installed and SSH activated. Once I run the command `make`, it gives me the following warnings (First code). But then I run `make install` command, it shows that I got Syntax error (second code at the bottom). Could you please help me to figure it out and finish the installing the tool? 
Also, could you let me know what routers I can buy to try this tool at home? 

Thanks!

```
~/Downloads/csi-monitor-master/csi-device-manager$ make
gcc -pthread -c ./src/csi_fun.c -o ./build/csi_fun.o
./src/csi_fun.c: In function ‘record_status’:
./src/csi_fun.c:140:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[0] << 56) & 0x00000000000000ff) | ((buf_addr[1] << 48) &
                           ^
./src/csi_fun.c:140:72: warning: left shift count >= width of type [-Wshift-count-overflow]
          ((buf_addr[0] << 56) & 0x00000000000000ff) | ((buf_addr[1] << 48) & 0x
                                                                     ^
./src/csi_fun.c:141:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[2] << 40) & 0x0000000000ff0000) | ((buf_addr[3] << 32) &
                           ^
./src/csi_fun.c:141:72: warning: left shift count >= width of type [-Wshift-count-overflow]
          ((buf_addr[2] << 40) & 0x0000000000ff0000) | ((buf_addr[3] << 32) & 0x
                                                                     ^
./src/csi_fun.c:151:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[7] << 56) & 0x00000000000000ff) | ((buf_addr[6] << 48) &
                           ^
./src/csi_fun.c:151:72: warning: left shift count >= width of type [-Wshift-count-overflow]
          ((buf_addr[7] << 56) & 0x00000000000000ff) | ((buf_addr[6] << 48) & 0x
                                                                     ^
./src/csi_fun.c:152:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[5] << 40) & 0x0000000000ff0000) | ((buf_addr[4] << 32) &
                           ^
./src/csi_fun.c:152:72: warning: left shift count >= width of type [-Wshift-count-overflow]
          ((buf_addr[5] << 40) & 0x0000000000ff0000) | ((buf_addr[4] << 32) & 0x
                                                                     ^
gcc -pthread -c ./src/socket.c -o ./build/socket.o
gcc -pthread -c ./src/sender.c -o ./build/sender.o
gcc -pthread -c ./src/csi_collector.c -o ./build/csi_collector.o
gcc -pthread -c ./src/main.c -o ./build/main.o
gcc -pthread ./build/csi_fun.o ./build/socket.o ./build/sender.o ./build/csi_collector.o ./build/main.o -o ./build/csi_device_manager
```

`~/Downloads/csi-monitor-master/csi-device-manager$ make install`
`/bin/sh: 25: Syntax error: Unterminated quoted string`
`Makefile:43: recipe for target 'install' failed`
`make: *** [install] Error 2`

**Comment by brunosoaresds** [comment]
Problem fixed on the referenced commit.

About your question, i think you can use the recommended routers on the Xie OpenWrt project page because i haven't tested CSI using off-the-shelf routers.

Best.,

**Comment by RusifE** [comment]
Thank you so much for the update! Also, could you please let me know why
would not csi_monitor_gui work in Matlab to open the gui for CSI tool? I am
in the csi-device-manager foldelr and typed the command, but I receive
"Undefined function or variable 'csi_monitor_gui'."

Thank you so much for your time and help!

![Matlab](https://user-images.githubusercontent.com/22744599/59124750-7ff87100-892e-11e9-8508-11dd8b67e185.png)

**Comment by brunosoaresds** [comment]
You need to go to the gui folder (where the csi_monitor_gui.m file is available) or you need to include that directory to your working path on matlab.

**Comment by RusifE** [comment]
> You need to go to the gui folder (where the csi_monitor_gui.m file is available) or you need to include that directory to your working path on matlab.

It worked! I opened up the csi_monitor_gui folder and run the command, and the GUI opened up. Thank you! 

Another issue I got is after I run the command csi_monitor_gui and opened up the GUI window. On matlab, I got errors (attach in the following picture). Is that because I have not connected any device yet / have not configured the CSI Monitor GUI correctly?

Thanks for the help!

**Comment by brunosoaresds** [comment]
you have not attached the picture.

**Comment by RusifE** [comment]
> you have not attached the picture.

I am sorry about that. Here it is.
![Matlab2](https://user-images.githubusercontent.com/22744599/59127033-87227d80-8934-11e9-9dbe-4543850e6e7e.png)

**Comment by brunosoaresds** [comment]
@RusifE try to rename csi_monitor_gui.m and csi_monitor_gui.fig to realtime_view.m/.fig respectively. That was the first name of this files, maybe i need to change something on .fig file to make it works. After renaming you need to open using realtime_view command.

**Comment by RusifE** [comment]
@brunosoaresds ,
Yes, that worked! Also, run the command realtime_view instead of csi_monitor_gui since renamed it. Was wondered why it caused the issue?

Thanks for the help!

**Comment by aynurm** [comment]
Hi, I have the first issue up there. After I fixed the quotation mark, I am still receiving the same error. Any other suggestions?

`csi-device-manager$ make
gcc -pthread -c ./src/csi_fun.c -o ./build/csi_fun.o
./src/csi_fun.c: In function ‘record_status’:
./src/csi_fun.c:140:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[0] << 56) & 0x00000000000000ff) | ((buf_addr[1] << 48) & 0x000000000000ff00) | 
                           ^
./src/csi_fun.c:140:72: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[0] << 56) & 0x00000000000000ff) | ((buf_addr[1] << 48) & 0x000000000000ff00) | 
                                                                        ^
./src/csi_fun.c:141:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[2] << 40) & 0x0000000000ff0000) | ((buf_addr[3] << 32) & 0x00000000ff000000) | 
                           ^
./src/csi_fun.c:141:72: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[2] << 40) & 0x0000000000ff0000) | ((buf_addr[3] << 32) & 0x00000000ff000000) | 
                                                                        ^
./src/csi_fun.c:151:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[7] << 56) & 0x00000000000000ff) | ((buf_addr[6] << 48) & 0x000000000000ff00) | 
                           ^
./src/csi_fun.c:151:72: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[7] << 56) & 0x00000000000000ff) | ((buf_addr[6] << 48) & 0x000000000000ff00) | 
                                                                        ^
./src/csi_fun.c:152:27: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[5] << 40) & 0x0000000000ff0000) | ((buf_addr[4] << 32) & 0x00000000ff000000) | 
                           ^
./src/csi_fun.c:152:72: warning: left shift count >= width of type [-Wshift-count-overflow]
             ((buf_addr[5] << 40) & 0x0000000000ff0000) | ((buf_addr[4] << 32) & 0x00000000ff000000) | 
                                                                        ^
gcc -pthread -c ./src/socket.c -o ./build/socket.o
gcc -pthread -c ./src/sender.c -o ./build/sender.o
gcc -pthread -c ./src/csi_collector.c -o ./build/csi_collector.o
gcc -pthread -c ./src/main.c -o ./build/main.o
gcc -pthread ./build/csi_fun.o ./build/socket.o ./build/sender.o ./build/csi_collector.o ./build/main.o -o ./build/csi_device_manager
`

This is my Makefile: 
`SRC_DIR = ./src
BUILD_DIR = ./build
BIN_PATH = $(BUILD_DIR)/csi_device_manager
DAEMON_FILE_PATH = ./init/csi-device-manager.daemon

INSTALLATION_DIR = /opt/csi-device-manager
INSTALLATION_BIN_PATH = $(INSTALLATION_DIR)/csi_device_manager
INTERFACE_ID_FILE = $(INSTALLATION_DIR)/interface_id
PORT_ID_FILE = $(INSTALLATION_DIR)/port_id
INIT_FILE_PATH = /etc/init.d/csi-device-manager
INSTALLATION_OUTPUT_FILES_DIR = $(INSTALLATION_DIR)/outputs

OBJS = csi_fun.o socket.o sender.o csi_collector.o main.o
BUILD_OBJS = $(BUILD_DIR)/csi_fun.o $(BUILD_DIR)/socket.o $(BUILD_DIR)/sender.o $(BUILD_DIR)/csi_collector.o $(BUILD_DIR)/main.o
CC = gcc -pthread

csi_device_manager: $(OBJS)
	@mkdir -p $(BUILD_DIR)
	$(CC) $(BUILD_OBJS) -o $(BIN_PATH)
csi_fun.o: $(SRC_DIR)/csi_fun.c $(SRC_DIR)/csi_fun.h
	@mkdir -p $(BUILD_DIR)
	$(CC) -c $(SRC_DIR)/csi_fun.c -o $(BUILD_DIR)/csi_fun.o
socket.o: $(SRC_DIR)/socket.c $(SRC_DIR)/socket.h
	@mkdir -p $(BUILD_DIR)
	$(CC) -c $(SRC_DIR)/socket.c -o $(BUILD_DIR)/socket.o
sender.o: $(SRC_DIR)/sender.c $(SRC_DIR)/sender.h
	@mkdir -p $(BUILD_DIR)
	$(CC) -c $(SRC_DIR)/sender.c -o $(BUILD_DIR)/sender.o
csi_collector.o: $(SRC_DIR)/csi_collector.c $(SRC_DIR)/csi_collector.h
	@mkdir -p $(BUILD_DIR)
	$(CC) -c $(SRC_DIR)/csi_collector.c -o $(BUILD_DIR)/csi_collector.o
main.o: $(SRC_DIR)/main.c $(SRC_DIR)/csi_fun.h $(SRC_DIR)/socket.h $(SRC_DIR)/sender.h $(SRC_DIR)/csi_collector.h
	@mkdir -p $(BUILD_DIR)
	$(CC) -c $(SRC_DIR)/main.c -o $(BUILD_DIR)/main.o

clean:
	rm -f $(BUILD_DIR)/*.o $(BIN_PATH)
	@if [ -d "$(BUILD_DIR)" ]; then \
		rm -r $(BUILD_DIR); \
	fi

install:
	@if [ ! -d "$(BUILD_DIR)" ] || [ ! -f "$(BIN_PATH)" ] ; then \
		echo "Project not builded yet."; \
		exit 2; \
	else \
		if [ -d "$(INSTALLATION_DIR)" ]; then \
			$(INIT_FILE_PATH) force-stop; \
			update-rc.d -f csi-device-manager remove; \
			rm -r $(INSTALLATION_DIR); \
		fi; \
		mkdir $(INSTALLATION_DIR); \
		cp $(BIN_PATH) $(INSTALLATION_BIN_PATH); \
		cp $(DAEMON_FILE_PATH) $(INIT_FILE_PATH); \
		read -p "Enter WLAN interface that the CSI Device manager will manage:" interface_in; \
		echo "$$interface_in" > $(INTERFACE_ID_FILE); \
		read -p "Enter the server port to be used (Default/Enter: 3000):" port_in; \
		echo "$$port_in" > $(PORT_ID_FILE); \
		mkdir $(INSTALLATION_OUTPUT_FILES_DIR); \
		chmod a+x $(INIT_FILE_PATH); \
		update-rc.d csi-device-manager defaults; \
		echo "========== Congratulations!! =========="; \
		echo "======== Installation done :) ========="; \
 		echo "If you need to change server port or WLAN interface, please change '$(PORT_ID_FILE)' and '$(INTERFACE_ID_FILE)' files."; 
		echo "You can start the service running $(INIT_FILE_PATH) start"; \
		echo "============== All done! =============="; \
fi`

Thanks

**Comment by brunosoaresds** [comment]
@aynurm, this is only warnings, if you see build dir the program was successfully compiled. You can proceed without a problem.

**Comment by aynurm** [comment]
Great! Yes, build dir is available right now. Thank you

**Comment by aynurm** [comment]
My another question is when I try to start, it says missing job name as following. Could you please let me know what should I do?

Downloads/csi-monitor-master/csi-device-manager/init/csi-device-manager.daemon status
CSI Device Manager is not running!!!
admin@admin:~/Downloads/csi-monitor-master/csi-device-manager$ start
start: missing job name
Try `start --help' for more information.

**Comment by aynurm** [comment]
Hi, I have the following error. I try to start the csi. It says CSI Device Manager started but when I check the status of it, it says that it is not running. Could you please explain what should I do to fix it?

`
/Downloads/csi-monitor-master/csi-device-manager$ /home/admin/Downloads/csi-monitor-master/csi-device-manager/init/csi-device-manager.daemon start
CSI Device Manager started!
/Downloads/csi-monitor-master/csi-device-manager$ /home/admin/Downloads/csi-monitor-master/csi-device-manager/init/csi-device-manager.daemon status
CSI Device Manager is not running!!!

**Comment by aynurm** [comment]
Also, where I should run this command at? In my machine or in receiver/sender?
` hostapd -B scripts/hostapd<5|2.4>.conf`

**Comment by brunosoaresds** [comment]
After the installation, the service will be installed on system.d so you need to init using service csi-device-manager start and not calling the relative daemon script.

The hostapd you will run on the receiver or the sender (you need to choose what device will be the AP and who will be the client). The hostapd creates the AP.

**Comment by aynurm** [comment]
Hi @brunosoaresds ,

Even when I start it from init.d, the status shows that it is not running. Could you please explain why and how I can fix it? Also. could you please let me know how I can I check if hostapd is running on either receiver or the sender?

`~$ /etc/init.d/csi-device-manager start`
`
CSI Device Manager started!~$ /etc/init.d/csi-device-manager status`
`
CSI Device Manager is not running!!!
`

**Comment by brunosoaresds** [comment]
What is the output of the command if you run the chai manager binary directly on the /opt path?

About the hostapd you can check via ps aux and monitor the interface with iwconfig to see if the network was established

**Comment by gis1991** [comment]
I found the same problem.I am trying to install CSI on my ubuntu 14.04. I have Matlab and Python installed and SSH activated.I have received the csi by using xie tool.When I make.The warm is so on...

 install./bin/sh: 25: Syntax error: Unterminated quoted string  
make: *** [install] Error 2

you say you can use the recommended routers on the Xie OpenWrt project page because i haven't tested CSI using off-the-shelf routers.Does it mean I need to run the installing of Xie OpenWrt?
I only used the tool on ubuntu.

Thanks a lot!

**Comment by brunosoaresds** [comment]
Do you have updated the repo? I have fixed the quoted problem in the latest commit. About the router I have only used in my thesis the Ubuntu version too. But you can try (if you want to) use the openwrt version.
