### ISSUE TITLE
question about on csi-monitor

### ISSUE THREAD

**Issue by gis1991** [brunosoaresds/csi-monitor#5]
dear
 
       I have uesed atheros to receive the csi .Now I want to realtime-processing for csi.Your sourse is helpful to me. I want to ask the question about the csi-monitor.I do it as the introduction.When I make install ,it says a mistake. 
         Is it necessary to be in a folder(opt/)?

**Comment by brunosoaresds** [comment]
The installation directory points to /opt folder, but you can change the makefile and .service file to point to another place if you want.
