### ISSUE TITLE
Is it possible to use the CSI Monitor tool for just the log file?

### ISSUE THREAD

**Issue by ghost** [brunosoaresds/csi-monitor#6]
Is it possible to use this tool to analyze the data gathered from the Atheros Tool recv_CSI generated log files?

Or does this tool only do real-time monitoring?

**Comment by brunosoaresds** [comment]
Actually, we read log files from the system, but each file loaded is a one second trace that is stored and download from the python layer. Unfortunately there is not a way to read the trace directly from file, so you need to implement it by yourself, but I think that it’s not so difficult.
