### ISSUE TITLE
GUI not running: undefined function or variable 'realtime_view'

### ISSUE THREAD

**Issue by josemanjarrez92** [brunosoaresds/csi-monitor#7]
Hi @brunosoaresds 
I was trying to run your CSI monitor today and apparently there was a filename change that provoked this in MATLAB just by trying to run the GUI:

> >> csi_monitor_gui
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('csi_receiver_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('csi_sender_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('graph_window_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('sender_seconds_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('sender_packets_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('subcarriers_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('tx_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)realtime_view('rx_CreateFcn',hObject,eventdata,guidata(hObject)) 
> Undefined function or variable 'realtime_view'.

What do you suggest me to do or could you upload a fixed version?
Thank you

**Comment by brunosoaresds** [comment]
Try this: https://github.com/brunosoaresds/csi-monitor/issues/4#issuecomment-500167742

**Comment by josemanjarrez92** [comment]
That solved it. Thanks!
