### ISSUE TITLE
Could not connect to sender

### ISSUE THREAD

**Issue by josemanjarrez92** [brunosoaresds/csi-monitor#8]
Hi,
I have a hostapd-based network where sender is 10.10.0.1 and receiver is 10.10.0.2. I can ping between them with no issue. Both PCs have all the requirements for this tool, but when I run the GUI and introduce sender's IP it shows a 'could not connect to sender' error. I verified that the csi-device-manager service is running in both devices. What can I do?
Thanks

**Comment by brunosoaresds** [comment]
Hi @josemanjarrez92 ,

Probably the machine where you're running the GUI cant connect to the csi-device-manager. Try troubleshooting by telnet to the device-manager service port. Maybe you're not in the same network or the device manager is not running correctly.

**Comment by josemanjarrez92** [comment]
Hi @brunosoaresds , thanks for your reply. I can telnet the port, I allowed the port 3000 on both firewalls, they're in the same network, and service is running correctly at both. I notice that the port_id file was empty, so I wrote 3000 in both devices and restarted the service, but still nothing. It doesn't make any sense, apparently.

**Comment by brunosoaresds** [comment]
There is a problem in connection from the GUI to the device-managers in the specified ports. can you send a print-screen of gui error and gui console?

**Comment by josemanjarrez92** [comment]
Here it is

![image](https://user-images.githubusercontent.com/31453034/64626576-086a3000-d3bc-11e9-80a6-7d2e24eb1618.png)

**Comment by brunosoaresds** [comment]
Your computer could not connect to the device manager. Please try to change the disp command of could not connect to the sender to print the error, maybe it help us.

**Comment by josemanjarrez92** [comment]
This is super embarrassing...
I didn't install the Intrument Control Toolbox, so that's why the tcpip function wouldn't start. I installed the toolbox and that part worked very well. 

Now I have a new issue: No packets/CSI arriving. Here's a screenshot:

![imagen](https://user-images.githubusercontent.com/31453034/64815405-8290e500-d573-11e9-8887-73dfaded9705.png)

**Comment by brilliantsxy** [comment]
Hi,@josemanjarrez92
 I meet the same question with you,have you resovled it? could you do me a favour? 
it seems like  that all my input in GUI are same with you, and No packets/CSI arriving，too.
i'm happy to recieve your reply! thanks a lot.

**Comment by brilliantsxy** [comment]
Hi,@josemanjarrez92
 I meet the same question with you,have you resovled it? could you do me a favour? 
it seems like  that all my input in GUI are same with you, and No packets/CSI arriving，too.
i'm happy to recieve your reply! thanks a lot.

**Comment by brilliantsxy** [comment]
Hi,@josemanjarrez92
 I meet the same question with you,have you resovled it? could you do me a favour? 
it seems like  that all my input in GUI are same with you, and No packets/CSI arriving，too.
i'm happy to recieve your reply! thanks a lot.

**Comment by brunosoaresds** [comment]
Hello @brilliantsxy @josemanjarrez92.

Can you see if the python could make the ssh copies? I think thats a problem on csi traces files copy from devices to the machine where you are running the monitor gui. Please check if the csi trace files are being stored in both sender and receiver. After that, check if that files are being copied to the python layer folder.

**Comment by guhen10** [comment]
i met with the same problem.how can i check csi trace files. where is it stored .Could you please explain in deteail?

**Comment by FuXianxin-CODE** [comment]
I meet the same question that no packets/CSI arriving. Has someone solved this problem？ @brunosoaresds @josemanjarrez92 @brilliantsxy @guhen10  I'm happy to receive your reply! Thanks a lot.

**Comment by brunosoaresds** [comment]
Hi,

Check the csi-device-manager interface ID (maybe yours is not wlan0), and the /dev collection. Are you using Wang CSI driver modification? I tried to access its website but link was broken.

Best.,
